start-at-login = true
after-startup-command = ['exec-and-forget borders width=7']

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

accordion-padding = 50
default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'

on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
automatically-unhide-macos-hidden-apps = false

[workspace-to-monitor-force-assignment]
C = 'secondary'

[[on-window-detected]]
if.app-name-regex-substring = 'finder'
run = 'layout floating'

[key-mapping]
preset = 'qwerty'

[gaps]
inner.horizontal = 10
outer.left = 10
outer.right = 10
outer.bottom = 10
outer.top = 10

[mode.main.binding]

alt-ctrl-shift-f = 'fullscreen'
alt-ctrl-f = 'layout floating tiling'

alt-shift-left = 'join-with left'
alt-shift-down = 'join-with down'
alt-shift-up = 'join-with up'
alt-shift-right = 'join-with right'

alt-slash = 'layout horizontal vertical'
alt-comma = 'layout tiles accordion'

alt-j = 'focus left'
alt-k = 'focus down'
alt-i = 'focus up'
alt-l = 'focus right'

alt-shift-j = 'move left'
alt-shift-k = 'move down'
alt-shift-i = 'move up'
alt-shift-l = 'move right'

alt-shift-minus = 'resize smart -50'
alt-shift-equal = 'resize smart +50'

alt-q = 'exec-and-forget osascript -e "tell application (path to frontmost application as text) to quit"'
alt-w = 'exec-and-forget osascript -e "tell application \"System Events\" to keystroke \"w\" using command down"'
alt-enter = 'exec-and-forget WINDOW_ID=$(aerospace list-windows --all | grep -i terminal | head -1 | cut -d " " -f1); if [ -n "$WINDOW_ID" ]; then aerospace focus --window-id $WINDOW_ID; else open -a Terminal; fi'

alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-a = 'workspace A'

alt-shift-1 = 'move-node-to-workspace 1 --focus-follows-window'
alt-shift-2 = 'move-node-to-workspace 2 --focus-follows-window'
alt-shift-3 = 'move-node-to-workspace 3 --focus-follows-window'
alt-shift-4 = 'move-node-to-workspace 4 --focus-follows-window'
alt-shift-a = 'move-node-to-workspace A --focus-follows-window'

alt-leftSquareBracket = 'focus-monitor --wrap-around prev'
alt-rightSquareBracket = 'focus-monitor --wrap-around next'
alt-shift-leftSquareBracket = 'move-node-to-monitor --wrap-around prev'
alt-shift-rightSquareBracket = 'move-node-to-monitor --wrap-around next'

alt-tab = 'workspace-back-and-forth'
alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

alt-shift-semicolon = 'mode service'

[mode.service.binding]
esc = ['reload-config', 'mode main']
r = ['flatten-workspace-tree', 'mode main']
f = ['layout floating tiling', 'mode main']
backspace = ['close-all-windows-but-current', 'mode main']
